### PR TITLE
Merging great changes back upstream here

### PR DESCRIPTION
**Pull request by terafin**
Hi @DarkSupremo! Awesome work here, going to pull some of the changes upstream, if that's ok with you! I will remove the docker-compose files, etc that are private to your stuff!

### CODE REVIEW

**Comment by terafin** [comment]
Actually, this might be a hard way to do it... need to start from a branch. Maybe the easiest thing to do is to stage the changes again, and attribute the commits...

**Comment by uilton-oliveira** [comment]
Yeah, probably is best to create an branch, remove the stuffs you don't want then merge with master.
That's the spirit of open source :)

**Comment by terafin** [comment]
@DarkSupremo - Thanks for the quick response! Generally I've gone the path of fork, then on that fork, make a branch, submit the PR from the fork/branch to upstream master. 

I'm happy to help collaborate in your fork (but don't have permissions) - or was your proposal something else? (Sorry for the dumb questions, and thanks for the fixes!)

**Comment by uilton-oliveira** [comment]
Yeah, i think that the path of an fork, branch and PR is the most common for that.

**Comment by terafin** [comment]
I can't double fork something in my account, but I can make a new org that does it.

**Comment by uilton-oliveira** [comment]
You can just create the pull request to an different branch, do the changes you wish and push it to master. That would work too...

**Pull request closed without merging**
